@startuml test_er
' Entity01 }|..|| Entity02
' Entity03 }o..o| Entity04
' Entity05 ||--o{ Entity06
' Entity07 |o--|| Entity08

entity "ユーザー" as user {
  id
  --
  ユーザ名
  パスワード
  所属
}

entity "PC情報" as pc_info {
  id
  --
  メーカー ID
  型番
  シリアル番号
  タイプID
  更新日
}

entity "PC情報詳細" as pc_info_detail {
  id
  --
  PC情報ID
  CPU ID
  メモリ ID
  OS ID
  ストレージ ID
  セットアップ日付
  使用ユーザ
  更新者
  メモ
}

user --o{ pc_info
pc_info -- pc_info_detail
@enduml