@url = http://localhost:3000

###
GET {{url}}

### 認証
# @name auth
POST {{url}}/login
Content-Type: application/json

{
  "userId": "motosbt",
  "password": "password"
}

###
@token = {{auth.response.body.$.token}}


################## User ###################
### 全ユーザ取得
GET {{url}}/users
Authorization: Bearer {{token}}

### ユーザ取得
GET {{url}}/users/motosbt
Authorization: Bearer {{token}}