@url = http://localhost:3000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inh4eHgiLCJpYXQiOjE2NjEyOTg0NzIsImV4cCI6MTY2MTMwMjA3Mn0.FNIOG371xTl2_33ZRFtyMJRLbg89Gmcz4BQupxKgLzQ

###
GET {{url}}

### 認証
POST {{url}}/login
Content-Type: application/json

{
  "username": "xxxx",
  "password": "xxxx"
}

### 認証あり
GET {{url}}/users
Authorization: {{token}}