@url = http://localhost:3000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inh4eHgiLCJpYXQiOjE2NjI3MDkzMTUsImV4cCI6MTY2MjcxMjkxNX0.mdenrgR7p9pWwYPMLLR_k9KY9Cv_pWSf6YJFffKpG2Q

###
GET {{url}}

### 認証
POST {{url}}/login
Content-Type: application/json

{
  "userId": "motosbt",
  "password": "password"
}

### 全ユーザ取得
GET {{url}}/users
Authorization: {{token}}

### ユーザ取得
GET {{url}}/users/motosbt
Authorization: {{token}}