@url = http://localhost:3000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inh4eHgiLCJpYXQiOjE2NjExMDkxOTIsImV4cCI6MTY2MTExMjc5Mn0.AJTYZovEAYzG9HRCKdYEPYKsTKsm8UOlzePLfTDqylA

###
GET {{url}}

### 認証
POST {{url}}/login
Content-Type: application/json

{
  "username": "xxxx",
  "password": "xxxx"
}

### 認証あり
GET {{url}}/users
Authorization: {{token}}